apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java-app-deployment
  labels:
    app: my-java-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-java-app
  template:
    metadata:
      labels:
        app: my-java-app
    spec:
      serviceAccountName: whatap
      containers:
        - name: my-java-app
          image: whatap/kube-apm-helper:0.1.0
          ports:
            - containerPort: 8080
          env:
            - name: NODE_IP
              valueFrom: { fieldRef: { fieldPath: status.hostIP } }
            - name: NODE_NAME
              valueFrom: { fieldRef: { fieldPath: spec.nodeName } }
            - name: POD_NAME
              valueFrom: { fieldRef: { fieldPath: metadata.name } }
---
apiVersion: v1
kind: Service
metadata:
  name: my-java-app-service
spec:
  selector:
    app: my-java-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer