apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java-app-deployment
  namespace: whatap-monitoring
  labels:
    app: my-java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-java-app
  template:
    metadata:
      labels:
        app: my-java-app
    spec:
      containers:
        - name: my-java-app
          image: whatap/kube-apm-helper:0.1.0
          ports:
            - containerPort: 8080
          env:
            - name: WTP_CON_NAME
              value: "my-java-app"
            - name: NODE_IP
              valueFrom: { fieldRef: { fieldPath: status.hostIP } }
            - name: NODE_NAME
              valueFrom: { fieldRef: { fieldPath: spec.nodeName } }
            - name: POD_NAME
              valueFrom: { fieldRef: { fieldPath: metadata.name } }
            - name: POD_ID
              valueFrom: { fieldRef: { fieldPath: metadata.uid } }
          volumeMounts:
            - name: pod-path
              mountPath: /var/lib/kubelet/pods
      volumes:
        - name: pod-path
          hostPath:
            path: /var/lib/kubelet/pods
        - name: containerddomainsocket
          hostPath:
            path: /run/containerd/container.sock