apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-pod
  name: test-pod
spec:
  serviceAccountName: jykim
  containers:
  - image: nginx
    name: test-container
    resources: {}
    env:
    - name: get_apm_container_id_using_whatap
      value: "true"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

